# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ef10de6f54c78c4be55181e9fce27f66efcdfd5bff3ab58c8bbf7b04a39dce6c8339a0c5f52b6fd8281fbab125d26ed53cc69c065b82aa5925d9ee550a77e2d

test:
  secret_key_base: c4278d4fc3acae87d4924c34068b2b9342bba47ad50a9650a136cb674b707e75b635781214d7ba63cc0d6dd3bcf58b1dbfa6f413e26121edb0ae67880d04713f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
